# Generated by Django 3.1.7 on 2021-03-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('english', models.IntegerField(default=0)),
                ('maths', models.IntegerField(default=0)),
                ('teugu', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('total_percentage', models.IntegerField(default=0)),
            ],
        ),
    ]
